<?php

/**
 * @file
 * Provides import functionality for all entity types, from excel files.
 */

define('IMPORT_SOURCE_FILE', 'file');
define('IMPORT_SOURCE_URL', 'url');

use Drupal\excel_import\Entity\ImportFileEntity;
use Drupal\excel_import\Entity\ImportTypeEntity;
use Drupal\excel_import\Entity\MappingEntity;

/**
 * Implements hook_enable().
 */
function excel_import_enable() {
  $entity = new ImportTypeEntity();
  $entity->ensureEntityTypeCreated();

  $entity = new ImportFileEntity();
  $entity->ensureEntityTypeCreated();

  $entity = new MappingEntity();
  $entity->ensureEntityTypeCreated();
}

/**
 * Implements hook_menu().
 */
function excel_import_menu() {

  $items['admin/content/import'] = [
    'title' => 'Excel Import',
    'description' => 'Import excel files into different entities.',
    'position' => 'right',
    'weight' => -8,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => ['import excel files'],
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  ];

  $import_types = ImportTypeEntity::getAllEntities();

  foreach ($import_types as $import_type) {
    $type_url_str = excel_import_machine_name($import_type->title);
    $items['admin/content/import/' . $type_url_str] = [
      'title' => ucfirst($import_type->title),
      'title callback' => 'check_plain',
      'page callback' => 'excel_import__import_overview_page',
      'page arguments' => [$import_type],
      'access arguments' => ['import excel files'],
      'file' => 'excel_import.pages.inc',
      'file path' => drupal_get_path('module', 'excel_import') . '/includes',
    ];

    $items['admin/content/import/' . $type_url_str . '/mapping'] = [
      'title' => 'Add/Edit mapping',
      'title callback' => 'check_plain',
      'page callback' => 'excel_import__mapping_page',
      'page arguments' => [$import_type, 'admin/content/import/' . $type_url_str],
      'access arguments' => ['import excel files'],
      'file' => 'excel_import.pages.inc',
      'file path' => drupal_get_path('module', 'excel_import') . '/includes',
      'type' => MENU_LOCAL_ACTION,
    ];

    $items['admin/content/import/' . $type_url_str . '/edit'] = [
      'title' => 'Edit import type',
      'title callback' => 'check_plain',
      'page callback' => 'excel_import__import_type_edit',
      'page arguments' => [$import_type, 'admin/content/import/' . $type_url_str],
      'access arguments' => ['import excel files'],
      'file' => 'excel_import.pages.inc',
      'file path' => drupal_get_path('module', 'excel_import') . '/includes',
      'type' => MENU_LOCAL_ACTION,
    ];
  }

  $items['admin/content/import/%import_file/review'] = [
    'title' => 'Review sheet',
    'page callback' => 'excel_import__review_page',
    'page arguments' => [3],
    'access arguments' => ['import excel files'],
    'type' => MENU_CALLBACK,
    'file' => 'excel_import.pages.inc',
    'file path' => drupal_get_path('module', 'excel_import') . '/includes',
  ];

  $items['admin/content/import/%import_file/import'] = [
    'title' => 'Import sheet',
    'page callback' => 'excel_import__import_page',
    'page arguments' => [3],
    'access arguments' => ['import excel files'],
    'type' => MENU_CALLBACK,
    'file' => 'excel_import.pages.inc',
    'file path' => drupal_get_path('module', 'excel_import') . '/includes',
  ];

  return $items;
}

/**
 * Load callback for import file entity.
 *
 * @param $id
 * @return mixed
 */
function import_file_load($id) {
  return entity_load_single(ImportFileEntity::ENTITY_TYPE, $id);
}

/**
 * Implements hook_permission().
 */
function excel_import_permission() {
  return [
    'import excel files' => [
      'title' => t('Import excel files'),
    ],
  ];
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function excel_import_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link to add import type on 'admin/content/import' page.
  if ($root_path == 'admin/content/import') {
    $item = menu_get_item('admin/structure/entity-type/' . ImportTypeEntity::ENTITY_TYPE . '/' . ImportTypeEntity::BUNDLE . '/add');
    $item['localized_options']['query']['destination'] = 'admin/content/import';
    if ($item['access']) {
      $data['actions']['output'][] = [
        '#theme' => 'menu_local_action',
        '#link' => $item,
      ];
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function excel_import_form_alter(&$form, &$form_state, $form_id) {
  // Alter import file entity add forms.
  if ($form_id === 'eck__entity__form_add_' . ImportFileEntity::ENTITY_TYPE . '_' . ImportFileEntity::BUNDLE) {
    module_load_include('inc', 'excel_import', 'includes/excel_import.form_alter');
    excel_import_alter_import_file_add_form($form, $form_state, $form_id);
  }

  // Alter import type entity add forms.
  if ($form_id === 'eck__entity__form_add_' . ImportTypeEntity::ENTITY_TYPE . '_' . ImportTypeEntity::BUNDLE) {
    module_load_include('inc', 'excel_import', 'includes/excel_import.form_alter');
    excel_import_alter_import_type_add_form($form, $form_state, $form_id);
  }

  // Alter import type entity edit forms.
  if ($form_id === 'eck__entity__form_edit_' . ImportTypeEntity::ENTITY_TYPE . '_' . ImportTypeEntity::BUNDLE) {
    module_load_include('inc', 'excel_import', 'includes/excel_import.form_alter');
    excel_import_alter_import_type_add_form($form, $form_state, $form_id);
  }

  // Alter mapping entity add forms.
  if ($form_id === 'eck__entity__form_add_' . MappingEntity::ENTITY_TYPE . '_' . MappingEntity::BUNDLE) {
    module_load_include('inc', 'excel_import', 'includes/excel_import.form_alter');
    excel_import_alter_mapping_add_form($form, $form_state, $form_id);
  }

  // Alter mapping entity edit forms.
  if ($form_id === 'eck__entity__form_edit_' . MappingEntity::ENTITY_TYPE . '_' . MappingEntity::BUNDLE) {
    module_load_include('inc', 'excel_import', 'includes/excel_import.form_alter');
    excel_import_alter_mapping_add_form($form, $form_state, $form_id);
  }

}

/**
 * Implements hook_entity_presave().
 */
function excel_import_entity_presave($entity, $type) {
  if ($type == ImportFileEntity::ENTITY_TYPE &&
    (!isset($entity->title) || empty($entity->title))) {

    $wrapper = entity_metadata_wrapper(ImportFileEntity::ENTITY_TYPE, $entity);

    $import_source = (isset($wrapper->field_import_source) && !empty($wrapper->field_import_source->value())) ? $wrapper->field_import_source->value() : IMPORT_SOURCE_FILE;
    switch ($import_source) {
      case IMPORT_SOURCE_FILE:
        $file_value = $wrapper->field_import_file->value();
        $file = file_load($file_value['fid']);
        $file_name = $file->filename;
        break;

      case IMPORT_SOURCE_URL:
        $url_info = $wrapper->field_import_url->value();
        $path_info = pathinfo($url_info['url']);
        $file_name = $path_info['filename'];
        break;
    }
    $wrapper->title->set($file_name);
  }

  if ($type == MappingEntity::ENTITY_TYPE &&
    (!isset($entity->title) || empty($entity->title))) {

    $wrapper = entity_metadata_wrapper(MappingEntity::ENTITY_TYPE, $entity);
    $import_type_title = $wrapper->field_import_type->title->value();
    $wrapper->title->set(format_string('Mapping for @title', ['@title' => $import_type_title]));
  }
}

/**
 * Implements hook_views_api().
 */
function excel_import_views_api() {
  return [
    'api' => 3,
    'path' => drupal_get_path('module', 'excel_import') . '/includes/views',
    'template path' => drupal_get_path('module', 'excel_import') . '/themes',
  ];
}

/**
 * Implements hook_ctools_plugin_type().
 */
function excel_import_ctools_plugin_type() {
  $return = [];

  $return['import_processor'] = [
    'cache' => TRUE,
    'cache table' => 'cache',
    'use hooks' => FALSE,
    'classes' => ['class'],
  ];

  return $return;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function excel_import_ctools_plugin_directory($owner, $plugin_type) {
  switch ("$owner:$plugin_type") {
    case 'mapping_field:mapping_source':
    case 'mapping_field:mapping_destination':
    case 'excel_import:import_processor':
      return "plugins/$owner/$plugin_type";
  }

  return NULL;
}


/**
 * Create a machine name from user input.
 *
 * @param $string
 * @return string
 */
function excel_import_machine_name($string) {
  return strtolower(preg_replace('/[^a-zA-Z0-9-]+/', '-', $string));
}

/**
 * Load the mapping for an import type.
 * @param $import_type
 * @return mixed
 */
function excel_import_load_mapping($import_type) {
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', MappingEntity::ENTITY_TYPE)
    ->entityCondition('bundle', MappingEntity::BUNDLE)
    ->fieldCondition('field_import_type', 'target_id', $import_type->id)
    ->execute();

  if (!empty($result)) {
    $mapping_data = reset($result[MappingEntity::ENTITY_TYPE]);
    return entity_load_single(MappingEntity::ENTITY_TYPE, $mapping_data->id);
  }
}

/**
 * Get all mapping_destination plugins.
 *
 * @return mixed
 */
function excel_import_get_plugins($type) {
  ctools_include('plugins');
  return ctools_get_plugins('excel_import', $type);
}

/**
 * Get a mapping_destination plugin.
 *
 * @return mixed
 */
function excel_import_get_plugin($type, $plugin_name) {
  ctools_include('plugins');
  return ctools_get_plugins('excel_import', $type, $plugin_name);
}
